/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.DAOGeral;
import modelo.Chat;
import modelo.Conexao;

/**
 *
 * @author johan
 */
public class Tela2 extends javax.swing.JFrame {
    
    DAOGeral daoChat = new DAOGeral();
    Tela1 objtela1 = new Tela1();
    /**
     * Creates new form Tela2
     */
    
    String cargoS;
    String nomeS;
    
    public Tela2(String nome , String cargo) {
        initComponents();
        atualizarTabela();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/logohead.png")).getImage());
        legendaLogin.setText(nome);
        cargoS = cargo;
        nomeS = nome;
    }
    
    public void atualizarTabela(){
        listChat.clear();
        listChat.addAll(daoChat.getListaChat());
        int linha = listChat.size()-1;
        
        if(linha>=0)
        
        {
        tabelaChat.setRowSelectionInterval(linha, linha);
        tabelaChat.scrollRectToVisible(tabelaChat.getCellRect(linha,linha,true));
        }
    }
    
    public boolean validaCampos(){
        
        if(!(txtChat.getText().length()>0)){
            JOptionPane.showMessageDialog(null, "Insira a mensagem");
            txtChat.requestFocus();
            return false;
        }
        
        if(txtChat.getText().length()>30){
            JOptionPane.showMessageDialog(null, "São muitos dados, por favor insira somente até 30 letras, números, pontos ou caracteres");
            txtChat.requestFocus(); 
            return false;
        }
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listChat = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Chat>());
        jPanel1 = new javax.swing.JPanel();
        btnEnviarMensagem = new javax.swing.JButton();
        txtChat = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaChat = new javax.swing.JTable();
        legendaLogin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDados = new javax.swing.JMenu();
        btntotal = new javax.swing.JMenuItem();
        btnmapa = new javax.swing.JMenuItem();
        btnavisos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btncidade = new javax.swing.JMenuItem();
        btnfunci = new javax.swing.JMenuItem();
        btnveiculo = new javax.swing.JMenuItem();
        btnproduto = new javax.swing.JMenuItem();
        btnmarca = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btnversao = new javax.swing.JMenuItem();
        btnsair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btnEnviarMensagem.setText("Enviar");
        btnEnviarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMensagemActionPerformed(evt);
            }
        });

        tabelaChat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tabelaChat.setGridColor(new java.awt.Color(0, 0, 0));
        tabelaChat.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tabelaChat.setSelectionForeground(new java.awt.Color(0, 0, 0));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listChat, tabelaChat);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${mensagem}"));
        columnBinding.setColumnName("Mensagem");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tabelaChat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtChat)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnviarMensagem)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarMensagem)
                    .addComponent(txtChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        legendaLogin.setBackground(new java.awt.Color(204, 204, 204));
        legendaLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        legendaLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        legendaLogin.setText("Login");
        legendaLogin.setToolTipText("");
        legendaLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("A new future today!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        menuDados.setText("Dados");

        btntotal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });
        menuDados.add(btntotal);

        btnmapa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        btnmapa.setText("Mapa da rede");
        btnmapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmapaActionPerformed(evt);
            }
        });
        menuDados.add(btnmapa);

        btnavisos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        btnavisos.setText("Avisos");
        btnavisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnavisosActionPerformed(evt);
            }
        });
        menuDados.add(btnavisos);

        jMenuBar1.add(menuDados);

        jMenu2.setText("Edit");

        btncidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        btncidade.setText("Cidade");
        btncidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncidadeActionPerformed(evt);
            }
        });
        jMenu2.add(btncidade);

        btnfunci.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        btnfunci.setText("Funcionario");
        btnfunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfunciActionPerformed(evt);
            }
        });
        jMenu2.add(btnfunci);

        btnveiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        btnveiculo.setText("Veiculo");
        btnveiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnveiculoActionPerformed(evt);
            }
        });
        jMenu2.add(btnveiculo);

        btnproduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        btnproduto.setText("Produto");
        btnproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodutoActionPerformed(evt);
            }
        });
        jMenu2.add(btnproduto);

        btnmarca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        btnmarca.setText("Marca");
        btnmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarcaActionPerformed(evt);
            }
        });
        jMenu2.add(btnmarca);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Opções");

        btnversao.setText("Versão");
        btnversao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnversaoActionPerformed(evt);
            }
        });
        jMenu1.add(btnversao);

        btnsair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        btnsair.setText("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        jMenu1.add(btnsair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(legendaLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(legendaLogin)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        // TODO add your handling code here:
        if(cargoS.equals("Fundador")){
            TelaTotal form = new TelaTotal();
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else if(cargoS.equals("Gerente")){
            TelaTotal form = new TelaTotal();
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Seu cargo é "+cargoS+"/n e este cargo não tem este tipo de autorização");
        }
    }//GEN-LAST:event_btntotalActionPerformed

    private void btncidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncidadeActionPerformed
        // TODO add your handling code here:
        
        if(cargoS.equals("Fundador")){
        FormCidade form = new FormCidade(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else if(cargoS.equals("Gerente")){
        FormCidade form = new FormCidade(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else if(cargoS.equals("Vendedor")){
        FormCidade form = new FormCidade(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Seu cargo é "+cargoS+"/n e este cargo não tem este tipo de autorização");
        }
    }//GEN-LAST:event_btncidadeActionPerformed

    private void btnfunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfunciActionPerformed
        // TODO add your handling code here:
        if(cargoS.equals("Fundador")){
        FormFuncionario form = new FormFuncionario(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else if(cargoS.equals("Gerente")){
        FormFuncionario form = new FormFuncionario(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Seu cargo é "+cargoS+"/n e este cargo não tem este tipo de autorização");
        }
    }//GEN-LAST:event_btnfunciActionPerformed

    private void btnveiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnveiculoActionPerformed
        // TODO add your handling code here:
        if(cargoS.equals("Fundador")){
        FormVeiculo form = new FormVeiculo(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else if(cargoS.equals("Gerente")){
        FormVeiculo form = new FormVeiculo(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else if(cargoS.equals("Motorista")){
        FormVeiculo form = new FormVeiculo(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Seu cargo é "+cargoS+"/n e este cargo não tem este tipo de autorização");
        }
        
    }//GEN-LAST:event_btnveiculoActionPerformed

    private void btnprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodutoActionPerformed
        // TODO add your handling code here:
        if(cargoS.equals("Fundador")){
        FormProdutos form = new FormProdutos(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else if(cargoS.equals("Gerente")){
        FormProdutos form = new FormProdutos(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else if(cargoS.equals("Vendedor")){
        FormProdutos form = new FormProdutos(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Seu cargo é "+cargoS+"/n e este cargo não tem este tipo de autorização");
        }
    }//GEN-LAST:event_btnprodutoActionPerformed

    private void btnversaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnversaoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Sistema de Cadastro\nVersão 2.0\nDireitos Reservados");
    }//GEN-LAST:event_btnversaoActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed

    private void btnEnviarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMensagemActionPerformed
        // TODO add your handling code here:
        if(validaCampos()){
            
        String sql = "INSERT INTO chat VALUES (NULL, ? )";
        
        try  
        {
            PreparedStatement pst = Conexao.getPreparedStatement(sql);
            pst.setString(1, legendaLogin.getText()+": "+txtChat.getText());
            if(pst.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "Mensagem enviada com sucesso");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Mensagem não enviada");
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Erro de SQL: "+ex.getMessage());
        }
        atualizarTabela();
        }
    }//GEN-LAST:event_btnEnviarMensagemActionPerformed

    private void btnmapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmapaActionPerformed
        // TODO add your handling code here:
        Mapa form = new Mapa(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
    }//GEN-LAST:event_btnmapaActionPerformed

    private void btnavisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnavisosActionPerformed
        // TODO add your handling code here:
        if(cargoS.equals("Fundador")){
        TelaAvisos form = new TelaAvisos(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else if(cargoS.equals("Gerente")){
        TelaAvisos form = new TelaAvisos(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Seu cargo é "+cargoS+"/n e este cargo não tem este tipo de autorização");
        }
    }//GEN-LAST:event_btnavisosActionPerformed

    private void btnmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarcaActionPerformed
        // TODO add your handling code here:
        if(cargoS.equals("Fundador")){
        FormMarca form = new FormMarca(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else if(cargoS.equals("Gerente")){
        FormMarca form = new FormMarca(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else if(cargoS.equals("Vendedor")){
        FormMarca form = new FormMarca(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);// centraliza a janela
        form.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Seu cargo é "+cargoS+"/n e este cargo não tem este tipo de autorização");
        }
    }//GEN-LAST:event_btnmarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela2("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarMensagem;
    private javax.swing.JMenuItem btnavisos;
    private javax.swing.JMenuItem btncidade;
    private javax.swing.JMenuItem btnfunci;
    private javax.swing.JMenuItem btnmapa;
    private javax.swing.JMenuItem btnmarca;
    private javax.swing.JMenuItem btnproduto;
    private javax.swing.JMenuItem btnsair;
    private javax.swing.JMenuItem btntotal;
    private javax.swing.JMenuItem btnveiculo;
    private javax.swing.JMenuItem btnversao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel legendaLogin;
    private java.util.List<Chat> listChat;
    private javax.swing.JMenu menuDados;
    private javax.swing.JTable tabelaChat;
    private javax.swing.JTextField txtChat;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
